name: Calificador Frontend II

on:
  pull_request:
    branches: ['main']

jobs:
  evaluacion:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar formato (Prettier)
        run: npx prettier --check .

      - name: Revisar calidad de código (ESLint)
        run: npm run lint

      - name: Ejecutar Pruebas (Vitest)
        run: npm run test
